spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/playground?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      auto-commit: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
logging.level.org.springframework.jdbc.core.JdbcTemplate: WARN