spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:playground}?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:root}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:root}}
    hikari:
      maximum-pool-size: 10
      auto-commit: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
logging.level.org.springframework.jdbc.core.JdbcTemplate: WARN